"""empty message

Revision ID: 2be7d37278e6
Revises: bfadbcc9011a
Create Date: 2019-07-25 01:13:05.260905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2be7d37278e6'
down_revision = 'bfadbcc9011a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('title', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'title')
    # ### end Alembic commands ###
