"""empty message

Revision ID: 4300edf62173
Revises: 2be7d37278e6
Create Date: 2019-07-25 14:42:27.382583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4300edf62173'
down_revision = '2be7d37278e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessment', sa.Column('damage', sa.String(length=60), nullable=True))
    op.add_column('assessment', sa.Column('damage_pcnt', sa.Integer(), nullable=True))
    op.add_column('assessment', sa.Column('disaster_name', sa.String(length=60), nullable=True))
    op.add_column('assessment', sa.Column('disaster_type', sa.String(length=60), nullable=True))
    op.add_column('assessment', sa.Column('exterior', sa.String(length=60), nullable=True))
    op.add_column('assessment', sa.Column('interior', sa.String(length=60), nullable=True))
    op.add_column('assessment', sa.Column('other_damage', sa.String(length=60), nullable=True))
    op.drop_column('assessment', 'body')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessment', sa.Column('body', sa.VARCHAR(length=140), nullable=True))
    op.drop_column('assessment', 'other_damage')
    op.drop_column('assessment', 'interior')
    op.drop_column('assessment', 'exterior')
    op.drop_column('assessment', 'disaster_type')
    op.drop_column('assessment', 'disaster_name')
    op.drop_column('assessment', 'damage_pcnt')
    op.drop_column('assessment', 'damage')
    # ### end Alembic commands ###
