"""empty message

Revision ID: 5af179291c48
Revises: 3066b0d6563d
Create Date: 2019-07-30 22:40:53.829472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5af179291c48'
down_revision = '3066b0d6563d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessment', sa.Column('city_name', sa.String(length=60), nullable=True))
    op.add_column('assessment', sa.Column('formatted_address', sa.String(length=120), nullable=True))
    op.add_column('assessment', sa.Column('google_place_id', sa.String(length=40), nullable=True))
    op.add_column('assessment', sa.Column('lat', sa.String(length=25), nullable=True))
    op.add_column('assessment', sa.Column('lng', sa.String(length=25), nullable=True))
    op.add_column('assessment', sa.Column('postal_code', sa.String(length=12), nullable=True))
    op.add_column('assessment', sa.Column('raw_address', sa.String(length=80), nullable=True))
    op.add_column('assessment', sa.Column('state_abr', sa.String(length=5), nullable=True))
    op.add_column('assessment', sa.Column('street_name', sa.String(length=60), nullable=True))
    op.add_column('assessment', sa.Column('street_number', sa.String(length=10), nullable=True))
    op.add_column('assessment', sa.Column('street_pic', sa.String(length=100), nullable=True))
    op.add_column('assessment', sa.Column('zillow_baths', sa.String(length=3), nullable=True))
    op.add_column('assessment', sa.Column('zillow_bedrooms', sa.String(length=3), nullable=True))
    op.add_column('assessment', sa.Column('zillow_estimate', sa.String(length=10), nullable=True))
    op.drop_column('assessment', 'state')
    op.drop_column('assessment', 'body')
    op.drop_column('assessment', 'city')
    op.drop_column('assessment', 'address')
    op.drop_column('assessment', 'county')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessment', sa.Column('county', sa.VARCHAR(length=60), nullable=True))
    op.add_column('assessment', sa.Column('address', sa.VARCHAR(length=80), nullable=True))
    op.add_column('assessment', sa.Column('city', sa.VARCHAR(length=40), nullable=True))
    op.add_column('assessment', sa.Column('body', sa.VARCHAR(length=140), nullable=True))
    op.add_column('assessment', sa.Column('state', sa.VARCHAR(length=20), nullable=True))
    op.drop_column('assessment', 'zillow_estimate')
    op.drop_column('assessment', 'zillow_bedrooms')
    op.drop_column('assessment', 'zillow_baths')
    op.drop_column('assessment', 'street_pic')
    op.drop_column('assessment', 'street_number')
    op.drop_column('assessment', 'street_name')
    op.drop_column('assessment', 'state_abr')
    op.drop_column('assessment', 'raw_address')
    op.drop_column('assessment', 'postal_code')
    op.drop_column('assessment', 'lng')
    op.drop_column('assessment', 'lat')
    op.drop_column('assessment', 'google_place_id')
    op.drop_column('assessment', 'formatted_address')
    op.drop_column('assessment', 'city_name')
    # ### end Alembic commands ###
