"""empty message

Revision ID: a4063cb9208a
Revises: 5af179291c48
Create Date: 2019-07-31 15:46:32.084222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4063cb9208a'
down_revision = '5af179291c48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessment', sa.Column('agent_est', sa.String(length=15), nullable=True))
    op.add_column('assessment', sa.Column('applicant_est', sa.String(length=15), nullable=True))
    op.add_column('assessment', sa.Column('comments', sa.String(length=300), nullable=True))
    op.add_column('assessment', sa.Column('other_exterior', sa.String(length=60), nullable=True))
    op.add_column('assessment', sa.Column('other_interior', sa.String(length=60), nullable=True))
    op.drop_column('assessment', 'county')
    op.drop_column('assessment', 'body')
    op.drop_column('assessment', 'city')
    op.drop_column('assessment', 'address')
    op.drop_column('assessment', 'state')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessment', sa.Column('state', sa.VARCHAR(length=20), nullable=True))
    op.add_column('assessment', sa.Column('address', sa.VARCHAR(length=80), nullable=True))
    op.add_column('assessment', sa.Column('city', sa.VARCHAR(length=40), nullable=True))
    op.add_column('assessment', sa.Column('body', sa.VARCHAR(length=140), nullable=True))
    op.add_column('assessment', sa.Column('county', sa.VARCHAR(length=60), nullable=True))
    op.drop_column('assessment', 'other_interior')
    op.drop_column('assessment', 'other_exterior')
    op.drop_column('assessment', 'comments')
    op.drop_column('assessment', 'applicant_est')
    op.drop_column('assessment', 'agent_est')
    # ### end Alembic commands ###
