"""empty message

Revision ID: b8f2a201eb31
Revises: a4063cb9208a
Create Date: 2019-08-02 02:14:14.344836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8f2a201eb31'
down_revision = 'a4063cb9208a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('optimizer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('map_pic', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_optimizer_timestamp'), 'optimizer', ['timestamp'], unique=False)
    op.drop_column('assessment', 'state')
    op.drop_column('assessment', 'address')
    op.drop_column('assessment', 'county')
    op.drop_column('assessment', 'city')
    op.drop_column('assessment', 'damage_pcnt')
    op.drop_column('assessment', 'body')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessment', sa.Column('body', sa.VARCHAR(length=140), nullable=True))
    op.add_column('assessment', sa.Column('damage_pcnt', sa.INTEGER(), nullable=True))
    op.add_column('assessment', sa.Column('city', sa.VARCHAR(length=40), nullable=True))
    op.add_column('assessment', sa.Column('county', sa.VARCHAR(length=60), nullable=True))
    op.add_column('assessment', sa.Column('address', sa.VARCHAR(length=80), nullable=True))
    op.add_column('assessment', sa.Column('state', sa.VARCHAR(length=20), nullable=True))
    op.drop_index(op.f('ix_optimizer_timestamp'), table_name='optimizer')
    op.drop_table('optimizer')
    # ### end Alembic commands ###
